require("settings")
require("mappings")
require("packer-config")
require("colorschemes-config")
require("nvim-tree-config")
require("lsp-config.language-servers")
require("lsp-config.nvim-cmp")
require("lsp-config.null-ls")
require("lualine-config")
require("barbar-config")
require("treesitter-config")
require("comment-config")
require("nvim-ts-autotag-config")
require("nvim-autopairs-config")
require("gitsigns-config")
-- require("shade-config")

print(vim.fn.getcwd())
